import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  {
    name: "Strategy",
    slug: "strategy",
  },
  {
    name: "Family",
    slug: "family",
  },
  {
    name: "Party",
    slug: "party",
  },
  {
    name: "Cooperative",
    slug: "cooperative",
  },
  {
    name: "Card Games",
    slug: "card-games",
  },
];

const products = [
  {
    title: "Catan",
    slug: "catan",
    description: "Build settlements, trade resources and race to become the dominant civilization on Catan.",
    publisher: "Catan Studio",
    designer: "Klaus Teuber",
    minPlayers: 3,
    maxPlayers: 4,
    playTimeMinutes: 90,
    minAge: 10,
    complexityRating: 2.3,
    price: 599.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 20,
    reorderThreshold: 5,
  },
  {
    title: "Ticket to Ride",
    slug: "ticket-to-ride",
    description: "Collect train cards and claim railway routes across North America.",
    publisher: "Days of Wonder",
    designer: "Alan R. Moon",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 60,
    minAge: 8,
    complexityRating: 1.9,
    price: 749.99,
    imageUrl: null,
    categories: ["family", "strategy"],
    quantityOnHand: 15,
    reorderThreshold: 5,
  },
  {
    title: "Pandemic",
    slug: "pandemic",
    description: "Work together as a team of specialists to stop global disease outbreaks.",
    publisher: "Z-Man Games",
    designer: "Matt Leacock",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 8,
    complexityRating: 2.4,
    price: 649.99,
    imageUrl: null,
    categories: ["cooperative", "strategy"],
    quantityOnHand: 12,
    reorderThreshold: 4,
  },
  {
    title: "Codenames",
    slug: "codenames",
    description: "Give clever one-word clues to help your team identify secret agents.",
    publisher: "Czech Games Edition",
    designer: "Vlaada Chvátil",
    minPlayers: 4,
    maxPlayers: 8,
    playTimeMinutes: 20,
    minAge: 10,
    complexityRating: 1.3,
    price: 399.99,
    imageUrl: null,
    categories: ["party", "family"],
    quantityOnHand: 25,
    reorderThreshold: 5,
  },
  {
    title: "Uno",
    slug: "uno",
    description: "A fast-paced card game where players race to empty their hands.",
    publisher: "Mattel",
    designer: null,
    minPlayers: 2,
    maxPlayers: 10,
    playTimeMinutes: 15,
    minAge: 7,
    complexityRating: 1.1,
    price: 149.99,
    imageUrl: null,
    categories: ["card-games", "family", "party"],
    quantityOnHand: 40,
    reorderThreshold: 10,
  },
  {
    title: "Azul",
    slug: "azul",
    description: "Draft colourful tiles and create beautiful patterns while carefully managing your choices.",
    publisher: "Next Move Games",
    designer: "Michael Kiesling",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 8,
    complexityRating: 1.8,
    price: 699.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 18,
    reorderThreshold: 5,
  },
  {
    title: "Wingspan",
    slug: "wingspan",
    description: "Attract birds to your wildlife preserve and build a powerful engine of bird habitats.",
    publisher: "Stonemaier Games",
    designer: "Elizabeth Hargrave",
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 70,
    minAge: 14,
    complexityRating: 2.4,
    price: 899.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 10,
    reorderThreshold: 3,
  },
  {
    title: "Carcassonne",
    slug: "carcassonne",
    description: "Build a medieval landscape with tiles and strategically place your followers.",
    publisher: "Hans im Glück",
    designer: "Klaus-Jürgen Wrede",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 45,
    minAge: 7,
    complexityRating: 1.9,
    price: 549.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 16,
    reorderThreshold: 5,
  },
  {
    title: "Splendor",
    slug: "splendor",
    description: "Collect gems, purchase development cards and attract influential nobles.",
    publisher: "Space Cowboys",
    designer: "Marc André",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 1.8,
    price: 599.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 20,
    reorderThreshold: 5,
  },
  {
    title: "7 Wonders",
    slug: "7-wonders",
    description: "Develop your civilization through three ages and construct a legendary wonder.",
    publisher: "Repos Production",
    designer: "Antoine Bauza",
    minPlayers: 3,
    maxPlayers: 7,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 2.3,
    price: 699.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 14,
    reorderThreshold: 4,
  },
  {
    title: "7 Wonders Duel",
    slug: "7-wonders-duel",
    description: "Compete against one opponent to develop a powerful civilization across three ages.",
    publisher: "Repos Production",
    designer: "Antoine Bauza",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 2.2,
    price: 549.99,
    imageUrl: null,
    categories: ["strategy", "card-games"],
    quantityOnHand: 13,
    reorderThreshold: 4,
  },
  {
    title: "Terraforming Mars",
    slug: "terraforming-mars",
    description: "Corporations compete to transform Mars into a habitable planet.",
    publisher: "FryxGames",
    designer: "Jacob Fryxelius",
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 120,
    minAge: 12,
    complexityRating: 3.2,
    price: 999.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 8,
    reorderThreshold: 3,
  },
  {
    title: "Scythe",
    slug: "scythe",
    description: "Lead a faction through an alternate-history Europe filled with resources, mechs and territory.",
    publisher: "Stonemaier Games",
    designer: "Jamey Stegmaier",
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 115,
    minAge: 14,
    complexityRating: 3.4,
    price: 1099.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 7,
    reorderThreshold: 2,
  },
  {
    title: "King of Tokyo",
    slug: "king-of-tokyo",
    description: "Become a giant monster, roll dice and battle your opponents for control of Tokyo.",
    publisher: "IELLO",
    designer: "Richard Garfield",
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 30,
    minAge: 8,
    complexityRating: 1.5,
    price: 449.99,
    imageUrl: null,
    categories: ["party", "family"],
    quantityOnHand: 22,
    reorderThreshold: 5,
  },
  {
    title: "Sushi Go!",
    slug: "sushi-go",
    description: "Collect delicious sushi combinations in this quick and colourful card-drafting game.",
    publisher: "Gamewright",
    designer: "Phil Walker-Harding",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 15,
    minAge: 8,
    complexityRating: 1.2,
    price: 249.99,
    imageUrl: null,
    categories: ["card-games", "party", "family"],
    quantityOnHand: 30,
    reorderThreshold: 8,
  },
  {
    title: "Sushi Go Party!",
    slug: "sushi-go-party",
    description: "A larger version of Sushi Go! with many more card combinations and player options.",
    publisher: "Gamewright",
    designer: "Phil Walker-Harding",
    minPlayers: 2,
    maxPlayers: 8,
    playTimeMinutes: 30,
    minAge: 8,
    complexityRating: 1.3,
    price: 399.99,
    imageUrl: null,
    categories: ["card-games", "party", "family"],
    quantityOnHand: 18,
    reorderThreshold: 5,
  },
  {
    title: "Kingdomino",
    slug: "kingdomino",
    description: "Build your kingdom by drafting domino-shaped terrain tiles.",
    publisher: "Blue Orange",
    designer: "Bruno Cathala",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 20,
    minAge: 8,
    complexityRating: 1.2,
    price: 449.99,
    imageUrl: null,
    categories: ["family", "strategy"],
    quantityOnHand: 17,
    reorderThreshold: 5,
  },
  {
    title: "Dixit",
    slug: "dixit",
    description: "Use imaginative clues and beautiful artwork to guide other players toward your chosen card.",
    publisher: "Libellud",
    designer: "Jean-Louis Roubira",
    minPlayers: 3,
    maxPlayers: 8,
    playTimeMinutes: 30,
    minAge: 8,
    complexityRating: 1.2,
    price: 549.99,
    imageUrl: null,
    categories: ["party", "family"],
    quantityOnHand: 15,
    reorderThreshold: 4,
  },
  {
    title: "The Quacks of Quedlinburg",
    slug: "the-quacks-of-quedlinburg",
    description: "Push your luck by drawing ingredients to brew the most valuable potion.",
    publisher: "North Star Games",
    designer: "Wolfgang Warsch",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 10,
    complexityRating: 1.9,
    price: 749.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 11,
    reorderThreshold: 3,
  },
  {
    title: "Patchwork",
    slug: "patchwork",
    description: "Compete to create the most efficient quilt using colourful fabric pieces.",
    publisher: "Lookout Games",
    designer: "Uwe Rosenberg",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 30,
    minAge: 8,
    complexityRating: 1.6,
    price: 399.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 14,
    reorderThreshold: 4,
  },
  {
    title: "Love Letter",
    slug: "love-letter",
    description: "Use deduction and clever card play to deliver your letter to the princess.",
    publisher: "Z-Man Games",
    designer: "Seiji Kanai",
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMinutes: 20,
    minAge: 10,
    complexityRating: 1.2,
    price: 199.99,
    imageUrl: null,
    categories: ["card-games", "party"],
    quantityOnHand: 25,
    reorderThreshold: 7,
  },
  {
    title: "Dominion",
    slug: "dominion",
    description: "Build a personal deck of cards and expand your kingdom through strategic purchases.",
    publisher: "Rio Grande Games",
    designer: "Donald X. Vaccarino",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
    minAge: 13,
    complexityRating: 2.4,
    price: 649.99,
    imageUrl: null,
    categories: ["card-games", "strategy"],
    quantityOnHand: 10,
    reorderThreshold: 3,
  },
  {
    title: "Clank!",
    slug: "clank",
    description: "Explore a dangerous dungeon, steal treasures and try to escape before the dragon catches you.",
    publisher: "Renegade Game Studios",
    designer: "Paul Dennen",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 60,
    minAge: 13,
    complexityRating: 2.6,
    price: 799.99,
    imageUrl: null,
    categories: ["strategy", "card-games"],
    quantityOnHand: 9,
    reorderThreshold: 3,
  },
  {
    title: "Root",
    slug: "root",
    description: "Lead an asymmetric woodland faction in a battle for control of the forest.",
    publisher: "Leder Games",
    designer: "Cole Wehrle",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 90,
    minAge: 10,
    complexityRating: 3.8,
    price: 949.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 7,
    reorderThreshold: 2,
  },
  {
    title: "Gloomhaven: Jaws of the Lion",
    slug: "gloomhaven-jaws-of-the-lion",
    description: "Embark on a cooperative tactical dungeon-crawling adventure with a group of mercenaries.",
    publisher: "Cephalofair Games",
    designer: "Isaac Childres",
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 14,
    complexityRating: 3.6,
    price: 1199.99,
    imageUrl: null,
    categories: ["cooperative", "strategy"],
    quantityOnHand: 6,
    reorderThreshold: 2,
  },
  {
    title: "Cascadia",
    slug: "cascadia",
    description: "Create a harmonious Pacific Northwest ecosystem using habitats and wildlife.",
    publisher: "Flatout Games",
    designer: "Randy Flynn",
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 10,
    complexityRating: 1.9,
    price: 699.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 12,
    reorderThreshold: 4,
  },
  {
    title: "The Castles of Burgundy",
    slug: "castles-of-burgundy",
    description: "Develop a medieval estate through tile placement, trading and careful planning.",
    publisher: "Ravensburger",
    designer: "Stefan Feld",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 90,
    minAge: 12,
    complexityRating: 3.0,
    price: 799.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 8,
    reorderThreshold: 3,
  },
  {
    title: "Everdell",
    slug: "everdell",
    description: "Build a charming woodland city populated by hardworking forest creatures.",
    publisher: "Starling Games",
    designer: "James A. Wilson",
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 60,
    minAge: 10,
    complexityRating: 2.8,
    price: 899.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 9,
    reorderThreshold: 3,
  },
  {
    title: "Dune: Imperium",
    slug: "dune-imperium",
    description: "Lead a powerful faction and compete for influence, resources and control of Arrakis.",
    publisher: "Dire Wolf",
    designer: "Paul Dennen",
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 14,
    complexityRating: 3.5,
    price: 999.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 7,
    reorderThreshold: 2,
  },
  {
    title: "Heat: Pedal to the Metal",
    slug: "heat-pedal-to-the-metal",
    description: "Race high-speed cars around tracks while managing heat and pushing your engine to its limits.",
    publisher: "Days of Wonder",
    designer: "Asger Harding Granerud",
    minPlayers: 1,
    maxPlayers: 6,
    playTimeMinutes: 60,
    minAge: 10,
    complexityRating: 2.2,
    price: 899.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 8,
    reorderThreshold: 3,
  },
  {
    title: "Exploding Kittens",
    slug: "exploding-kittens",
    description: "Draw cards, avoid exploding kittens and use clever actions to survive.",
    publisher: "Exploding Kittens",
    designer: "Elan Lee",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 15,
    minAge: 7,
    complexityRating: 1.1,
    price: 249.99,
    imageUrl: null,
    categories: ["card-games", "party"],
    quantityOnHand: 30,
    reorderThreshold: 8,
  },
  {
    title: "Dobble",
    slug: "dobble",
    description: "A fast observation game where players race to spot matching symbols.",
    publisher: "Zygomatic",
    designer: "Denis Blanchot",
    minPlayers: 2,
    maxPlayers: 8,
    playTimeMinutes: 15,
    minAge: 6,
    complexityRating: 1.0,
    price: 199.99,
    imageUrl: null,
    categories: ["party", "family"],
    quantityOnHand: 35,
    reorderThreshold: 10,
  },
  {
    title: "Just One",
    slug: "just-one",
    description: "Work together to guess mystery words using unique one-word clues.",
    publisher: "Repos Production",
    designer: "Ludovic Roudy",
    minPlayers: 3,
    maxPlayers: 7,
    playTimeMinutes: 20,
    minAge: 8,
    complexityRating: 1.0,
    price: 349.99,
    imageUrl: null,
    categories: ["party", "family"],
    quantityOnHand: 20,
    reorderThreshold: 5,
  },
  {
    title: "Forbidden Island",
    slug: "forbidden-island",
    description: "Cooperate to recover four treasures before a sinking island disappears beneath the waves.",
    publisher: "Gamewright",
    designer: "Matt Leacock",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 1.7,
    price: 449.99,
    imageUrl: null,
    categories: ["cooperative", "family"],
    quantityOnHand: 12,
    reorderThreshold: 4,
  },
  {
    title: "The Crew: The Quest for Planet Nine",
    slug: "the-crew-quest-for-planet-nine",
    description: "Complete increasingly difficult cooperative missions through a clever trick-taking card game.",
    publisher: "Kosmos",
    designer: "Thomas Sing",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 20,
    minAge: 10,
    complexityRating: 2.0,
    price: 299.99,
    imageUrl: null,
    categories: ["cooperative", "card-games"],
    quantityOnHand: 16,
    reorderThreshold: 5,
  },
  {
    title: "Skull",
    slug: "skull",
    description: "Bluff, bid and push your luck without revealing the deadly skull.",
    publisher: "Space Cowboys",
    designer: "Hervé Marly",
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 1.4,
    price: 299.99,
    imageUrl: null,
    categories: ["party", "card-games"],
    quantityOnHand: 18,
    reorderThreshold: 5,
  },
  {
    title: "Lost Cities",
    slug: "lost-cities",
    description: "Plan expeditions carefully and decide when to commit your cards to dangerous discoveries.",
    publisher: "Kosmos",
    designer: "Reiner Knizia",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 1.5,
    price: 399.99,
    imageUrl: null,
    categories: ["card-games", "strategy"],
    quantityOnHand: 14,
    reorderThreshold: 4,
  },
  {
    title: "Jaipur",
    slug: "jaipur",
    description: "Trade valuable goods and compete to become the most successful merchant.",
    publisher: "Space Cowboys",
    designer: "Sébastien Pauchon",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 1.5,
    price: 449.99,
    imageUrl: null,
    categories: ["card-games", "strategy"],
    quantityOnHand: 13,
    reorderThreshold: 4,
  },
  {
    title: "Patchwork Doodle",
    slug: "patchwork-doodle",
    description: "Create colourful quilt designs by drawing and strategically filling your personal board.",
    publisher: "Lookout Games",
    designer: "Uwe Rosenberg",
    minPlayers: 1,
    maxPlayers: 6,
    playTimeMinutes: 20,
    minAge: 8,
    complexityRating: 1.3,
    price: 299.99,
    imageUrl: null,
    categories: ["family", "strategy"],
    quantityOnHand: 10,
    reorderThreshold: 3,
  },
  {
    title: "Ark Nova",
    slug: "ark-nova",
    description: "Plan and build a modern zoo while supporting conservation projects around the world.",
    publisher: "Capstone Games",
    designer: "Mathias Wigge",
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 150,
    minAge: 14,
    complexityRating: 3.7,
    price: 1299.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 5,
    reorderThreshold: 2,
  },
  {
    title: "Brass: Birmingham",
    slug: "brass-birmingham",
    description: "Develop industries and networks during the Industrial Revolution in Birmingham.",
    publisher: "Roxley",
    designer: "Gavan Brown",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 14,
    complexityRating: 4.0,
    price: 1199.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 5,
    reorderThreshold: 2,
  },
  {
    title: "Spirit Island",
    slug: "spirit-island",
    description: "Powerful spirits cooperate to defend their island against invading forces.",
    publisher: "Greater Than Games",
    designer: "R. Eric Reuss",
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMinutes: 120,
    minAge: 13,
    complexityRating: 4.0,
    price: 1099.99,
    imageUrl: null,
    categories: ["cooperative", "strategy"],
    quantityOnHand: 6,
    reorderThreshold: 2,
  },
  {
    title: "Betrayal at House on the Hill",
    slug: "betrayal-at-house-on-the-hill",
    description: "Explore a haunted mansion before one player turns against the rest.",
    publisher: "Avalon Hill",
    designer: "Bruce Glassco",
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMinutes: 60,
    minAge: 12,
    complexityRating: 2.4,
    price: 799.99,
    imageUrl: null,
    categories: ["party", "strategy"],
    quantityOnHand: 9,
    reorderThreshold: 3,
  },
  {
    title: "Mysterium",
    slug: "mysterium",
    description: "Work together to solve a supernatural murder mystery through mysterious visions.",
    publisher: "Libellud",
    designer: "Oleksandr Nevskiy",
    minPlayers: 2,
    maxPlayers: 7,
    playTimeMinutes: 45,
    minAge: 10,
    complexityRating: 1.9,
    price: 699.99,
    imageUrl: null,
    categories: ["cooperative", "party"],
    quantityOnHand: 10,
    reorderThreshold: 3,
  },
  {
    title: "Takenoko",
    slug: "takenoko",
    description: "Cultivate bamboo gardens and care for a hungry giant panda.",
    publisher: "Bombyx",
    designer: "Antoine Bauza",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 45,
    minAge: 8,
    complexityRating: 1.8,
    price: 649.99,
    imageUrl: null,
    categories: ["family", "strategy"],
    quantityOnHand: 11,
    reorderThreshold: 3,
  },
  {
    title: "Hanabi",
    slug: "hanabi",
    description: "Work together to create a spectacular fireworks display using limited information.",
    publisher: "Abacusspiele",
    designer: "Antoine Bauza",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 25,
    minAge: 8,
    complexityRating: 1.7,
    price: 249.99,
    imageUrl: null,
    categories: ["cooperative", "card-games"],
    quantityOnHand: 17,
    reorderThreshold: 5,
  },
  {
    title: "Hive",
    slug: "hive",
    description: "Outmanoeuvre your opponent by surrounding their queen bee with your insect pieces.",
    publisher: "Gen42",
    designer: "John Yianni",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 20,
    minAge: 9,
    complexityRating: 2.4,
    price: 449.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 15,
    reorderThreshold: 4,
  },
  {
    title: "Ticket to Ride: Europe",
    slug: "ticket-to-ride-europe",
    description: "Build railway routes across Europe while using tunnels, ferries and stations.",
    publisher: "Days of Wonder",
    designer: "Alan R. Moon",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 60,
    minAge: 8,
    complexityRating: 2.0,
    price: 799.99,
    imageUrl: null,
    categories: ["family", "strategy"],
    quantityOnHand: 13,
    reorderThreshold: 4,
  },
  {
    title: "Catan Junior",
    slug: "catan-junior",
    description: "A family-friendly version of Catan designed for younger players.",
    publisher: "Catan Studio",
    designer: "Benjamin Teuber",
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMinutes: 30,
    minAge: 6,
    complexityRating: 1.2,
    price: 499.99,
    imageUrl: null,
    categories: ["family"],
    quantityOnHand: 14,
    reorderThreshold: 4,
  },
  {
    title: "Wyrmspan",
    slug: "wyrmspan",
    description: "Build a sanctuary for dragons and attract an impressive collection of mythical creatures.",
    publisher: "Stonemaier Games",
    designer: "Connie Vogelmann",
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMinutes: 90,
    minAge: 14,
    complexityRating: 3.0,
    price: 999.99,
    imageUrl: null,
    categories: ["strategy"],
    quantityOnHand: 7,
    reorderThreshold: 2,
  },
  {
    title: "Forest Shuffle",
    slug: "forest-shuffle",
    description: "Create a thriving forest ecosystem by combining trees, plants and wildlife.",
    publisher: "Lookout Games",
    designer: "Kosch",
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMinutes: 60,
    minAge: 10,
    complexityRating: 2.4,
    price: 649.99,
    imageUrl: null,
    categories: ["strategy", "family"],
    quantityOnHand: 9,
    reorderThreshold: 3,
  },
  {
    title: "Sky Team",
    slug: "sky-team",
    description: "Cooperate as a pilot and co-pilot to land aircraft safely at airports around the world.",
    publisher: "Scorpion Masqué",
    designer: "Luc Rémond",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 20,
    minAge: 12,
    complexityRating: 2.1,
    price: 499.99,
    imageUrl: null,
    categories: ["cooperative", "strategy"],
    quantityOnHand: 10,
    reorderThreshold: 3,
  },
  {
    title: "The Lord of the Rings: Duel for Middle-earth",
    slug: "lord-of-the-rings-duel-for-middle-earth",
    description: "Compete for control of Middle-earth in a strategic two-player card-driven battle.",
    publisher: "Repos Production",
    designer: "Antoine Bauza",
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMinutes: 30,
    minAge: 10,
    complexityRating: 2.2,
    price: 649.99,
    imageUrl: null,
    categories: ["strategy", "card-games"],
    quantityOnHand: 8,
    reorderThreshold: 3,
  },
];
async function main() {
  console.log("🌱 Starting database seed...");

  // Roles
  const roles = ["customer", "admin"];

  for (const name of roles) {
    await prisma.role.upsert({
      where: { name },
      update: {},
      create: { name },
    });
  }

  console.log("✓ Roles seeded");

  // Categories
  const categoryMap = new Map();

  for (const category of categories) {
    const record = await prisma.category.upsert({
      where: { slug: category.slug },
      update: {
        name: category.name,
      },
      create: category,
    });

    categoryMap.set(record.slug, record.id);
  }

  console.log("✓ Categories seeded");

  // Products, category relationships and inventory
  for (const product of products) {
    const {
      categories: productCategories,
      quantityOnHand,
      reorderThreshold,
      ...productData
    } = product;

    const createdProduct = await prisma.product.upsert({
      where: { slug: product.slug },
      update: productData,
      create: productData,
    });

    for (const categorySlug of productCategories) {
      const categoryId = categoryMap.get(categorySlug);

      if (!categoryId) {
        throw new Error(
          `Category "${categorySlug}" was not found while seeding ${product.title}.`,
        );
      }

      await prisma.productCategory.upsert({
        where: {
          productId_categoryId: {
            productId: createdProduct.id,
            categoryId,
          },
        },
        update: {},
        create: {
          productId: createdProduct.id,
          categoryId,
        },
      });
    }

    await prisma.inventory.upsert({
      where: {
        productId: createdProduct.id,
      },
      update: {
        quantityOnHand,
        reorderThreshold,
      },
      create: {
        productId: createdProduct.id,
        quantityOnHand,
        reorderThreshold,
      },
    });
  }

  console.log("✓ Products seeded");
  console.log("✓ Product categories seeded");
  console.log("✓ Inventory seeded");
  console.log("🌱 Database seed completed successfully.");
}

main()
  .catch((error) => {
    console.error("❌ Database seed failed:");
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });