/*
  Warnings:

  - You are about to drop the `mechanics` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `product_mechanics` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "product_mechanics" DROP CONSTRAINT "product_mechanics_mechanic_id_fkey";

-- DropForeignKey
ALTER TABLE "product_mechanics" DROP CONSTRAINT "product_mechanics_product_id_fkey";

-- AlterTable
ALTER TABLE "cart_items" ALTER COLUMN "added_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "inventory" ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "payments" ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "products" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "reviews" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6);

-- DropTable
DROP TABLE "mechanics";

-- DropTable
DROP TABLE "product_mechanics";

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "token_hash" VARCHAR(255) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Data integrity constraints (NFR7) — not generated by Prisma, added by hand per review feedback

ALTER TABLE reviews ADD CONSTRAINT reviews_rating_check
  CHECK (rating BETWEEN 1 AND 5);

ALTER TABLE products ADD CONSTRAINT products_price_check
  CHECK (price >= 0);

ALTER TABLE products ADD CONSTRAINT products_complexity_check
  CHECK (complexity_rating BETWEEN 0.0 AND 5.0);

ALTER TABLE cart_items ADD CONSTRAINT cart_items_quantity_check
  CHECK (quantity > 0);

ALTER TABLE inventory ADD CONSTRAINT inventory_quantity_check
  CHECK (quantity_on_hand >= 0);
